# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
#
# stop db
# stop service
# dbclose, dbunload
# ttdaemonadmin stop
---

- name: set paths for mgmt servers
  include_tasks:    roles/mgmtinstances/tasks/mgmt-path.yaml

- name: attempt load (restarttimeout=={{ restarttimeout }})
  shell:            "{{ mgmt }} ttgridadmin dbload {{ dbname }} -wait {{ restarttimeout }}"
  register:         dbload
  become:           true
  become_user:      oracle
  run_once:         true

- name: attempt open (restarttimeout=={{ restarttimeout }})
  shell:            "{{ mgmt }} ttgridadmin dbopen {{ dbname }} -wait {{ restarttimeout }}"
  register:         dbopen
  become:           true
  become_user:      oracle
  run_once:         true


- name: check dbstatus
  shell:            "{{ mgmt }} ttgridadmin dbstatus {{ dbname }} --replicaset"
  register:         dbstatus
  ignore_errors:    true
  become:           true
  become_user:      oracle
  run_once:         true

- name: display dbstatus
  debug:
    msg:            "{{ dbstatus.stdout_lines }}"
  run_once:         true


