# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
#
# start db services
# load, open
---

- name: start db services
  include_tasks:    roles/mgmtinstances/tasks/db-service.yaml
  when:             inventory_hostname in groups['db-addresses']

- name: load / open db
  include_tasks:    roles/dbrestart/tasks/dbstartops.yaml
  when:             inventory_hostname in groups['mgmt-addresses']



