# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
#
# mgmt paths
# db service name
# db instance paths
---

- name: get path to instance
  shell:            "ls {{ ttinstancedir }} | grep instance"
  register:         instpath
  become:           true
  become_user:      oracle
#  ignore_errors:    true

- name: debug info
  debug:
    msg: "host: {{ inventory_hostname }} instpath: {{ instpath.stdout }}"

- name: set db service name
  set_fact:
    dbservicename:  "{{ inventory_hostname }}.service"
    ttinstancepath: "{{ ttinstancedir }}/{{ instpath.stdout }}"



