# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
---
#
# Kernel other OS related utility settings 
# Kernel parameter values chosen here are OCI default for semaphores and shared memory
#
- name: create directory to avoid warning
  file:
    state:     directory
    path:      "/root/.ansible/tmp"
    owner:     root
    group:     root
    mode:      0700
    recurse:   true

# Values chosen are OCI defaults
# They are here for completeness

- name: semaphores
  sysctl: 
    name:        kernel.sem
    value:       "32000	1024000000	500	32000"
    sysctl_set:  yes
    state:       present
    reload:      yes

- name: shared memory shmmax
  sysctl:
    name:        kernel.shmmax
    value:       18446744073692774399
    sysctl_set:  yes
    state:       present
    reload:      yes

- name: shared memory shmall
  sysctl:
    name:        kernel.shmall
    value:       18446744073692774399
    sysctl_set:  yes
    state:       present
    reload:      yes

- name: shared memory shmmni
  sysctl:
    name:        kernel.shmmni
    value:       4096
    sysctl_set:  yes
    state:       present
    reload:      yes

# These values are not default on OCI

# This setting is from Bug 27901681
- name: shorter timeout for high availability
  sysctl:
    name:        net.ipv4.tcp_retries2
    value:       3
    sysctl_set:  yes
    state:       present
    reload:      yes

# Enable enough for oodles of connections
- name: somaxconn
  sysctl:
    name:        net.core.somaxconn
    value:       4096
    sysctl_set:  yes
    state:       present
    reload:      yes 

# large pages
- name: use logbufmb in large page calcs
  shell:        sed -n -e 's/LogBufMB=//p' roles/mgmtinstances/templates/attributes.dbdef.j2
  args:  
    warn:       false
  register:     logbufmb
  delegate_to:  localhost

- name: use connections in large page calcs
  shell:        sed -n -e 's/Connections=//p' roles/mgmtinstances/templates/attributes.dbdef.j2
  args:
    warn:       false
  register:     conns
  delegate_to:  localhost

- name: configure large pages
  sysctl:
    name:        vm.nr_hugepages
    # perm + temp + logbuf + conns + [management db + 2*plsql seg]
    value:       "{{ ((permsize|int + tempsize|int + logbufmb.stdout|int + (conns.stdout|int * 0.05) + (384+128*2)) / 2)|int }}"
    sysctl_set:  yes
    state:       present
    reload:      yes

- name: limits.conf nofile memlock core nproc
  blockinfile:
    path: /etc/security/limits.conf
    block: |
        *       hard nofile 65536
        *       soft nofile 65536
        *       hard memlock unlimited
        *       soft memlock unlimited
        *       hard core unlimited
        *       soft core unlimited
        *       hard nproc unlimited
        *       soft nproc unlimited

- name: limits.conf nproc
  blockinfile:
    path: /etc/security/limits.d/20-nproc.conf
    block: |
        oracle     soft    nproc     65536

- name: remove directory created to avoid warning
  file:
    state:     absent
    path:      "/root/.ansible"

# place holder for ntp
