# Copyright (c) 1999, 2018, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
---
# Run ttgridrollout to set up grid and database
#
- import_tasks: datainstance.yml
  become:       true

- import_tasks: create-grid.yml
  become:       true
  become_user:  oracle

