# Copyright (c) 1999, 2018, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
#
# Storage configuration
# If fsname is mounted, then do nothing
# Choices are LVM-RAID0, MDRAID-RAID10
# 
# Creating the file system using mdraid takes ~10 minutes < 1 hour
# Doesn't use more than 4 devices.
# 

- name: import tasks
  include_tasks: roles/datainstances/tasks/storage-common.yml

- name:  lvm-raid-0 
  yum:   
    name:        lvm2
    state:       present

- name: set common variables
  set_fact:
    vgname:      "vg{{ fsname | regex_replace('/') }}"
    lvname:      "lv{{ fsname | regex_replace('/') }}"
    stripesz:    ""

- name: set stripe size
  set_fact:
    stripesz:    "-I 128K -i {{ ndevices }}"
  when:          ndevices|int > 1

- name: align and 0 
  shell: |
    dd if=/dev/zero of="{{ item }}" bs=512 count=2048 > /dev/null 2>&1
    pvscan --cache
  with_items:
  - "{{ devices }}"
  ignore_errors: true

- name: partition disk
  parted:
    device:     "{{ item }}"
    number:     1
    align:      optimal
    label:      gpt
    state:      present
    unit:       GB
    part_start: 2048s
    part_end:   98%
    part_type:  extended
  with_items:
  - "{{ devices }}"

- name: for nvme just use device
  set_fact:
    sdevices: "{{ devices }}"
  when:       nvmedevs.stdout|length > 0

- name: set up volume group
  lvg: 
    vg:         "{{ vgname }}"
    pvs:        "{{ sdevices }}"
    pesize:     32
    state:      "present"

- name: set up logical volume
  lvol:
    lv:         "{{ lvname }}"
    vg:         "{{ vgname }}"
    state:      "present"
    active:     "yes"
    size:       "+100%FREE"
    force:      "yes"

- name: create filesystem      
  filesystem:
    dev:     "/dev/{{ vgname }}/{{ lvname }}"
    fstype:  "{{ fstype }}"

- name: mount filesystem
  mount: 
    src:     "/dev/{{ vgname }}/{{ lvname }}"
    path:    "{{ fsname }}"
    state:   mounted
    opts:    "{{ mntopts }}"
    passno:  2
    fstype:  ext4
             
