#
# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl

# Storage configuration
# Choices are LVM-RAID0, MDRAID-RAID10
# 
# Creating the file system using mdraid takes from 10 minutes < 1 hour
# 
# Below doesn't configure more than 4 devices.
---

- name: get nvme devices, no more than 4
  shell:         lsblk | awk '/^nvme/ {print $1}' | head -4
  register:      nvmedevs 

- name: fail if not nvme shape and md-raid-10
  fail:
    msg:         "Error: MD-RAID-10 only supported on nvme shapes"
  when:          storage == "MD-RAID-10" and nvmedevs.stdout_lines | length == 0

- name: start service for iscsi attach/detach
  include_tasks: "roles/datainstances/tasks/iscsi-service.yaml"
  register:      iscsirc
  when:          nvmedevs.stdout_lines | length == 0

- name: get block storage devices, no more than 4
  shell:         lsblk | awk '/^sd[b-z]/ {print $1}' | head -4 
  register:      blkvols 

- name: fail out if no devices for lvm
  fail: 
    msg:         "Error: No NVMe nor block storage devices found."
  when:          storage == "LVM-RAID-0" and nvmedevs.stdout_lines | length == 0 and blkvols.stdout_lines | length == 0

- name: fail out if too few devices for raid-10
  fail:
    msg:         "Error: insufficient number of devices found({{ nvmedevs.stdout_lines|length }}) [{{ nvmedevs.stdout }}].  For raid 10, need 4 devices"
  when:          storage == "MD-RAID-10" and nvmedevs.stdout_lines | length < 4 and blkvols.stdout_lines | length < 4

- name: set variables for nvme
  set_fact: 
    ndevices:    "{{ nvmedevs.stdout_lines|length }}"
    blkdevsfx:   "p1"
    mntopts:     "defaults,noatime,nofail"
    devices:     "{{ nvmedevs.stdout_lines|regex_replace('nvme','/dev/nvme') }}"
    #            common variable but here without suffix
    sdevices:    "{{ nvmedevs.stdout_lines|regex_replace('nvme','/dev/nvme') }}"
  when:          nvmedevs.stdout|length > 0

- name: set variables for block storage but favor nvme if present
  set_fact: 
    ndevices:    "{{ blkvols.stdout_lines | length }}"
    blkdevsfx:   "1"
    mntopts:     "defaults,_netdev,noatime,nofail"
    devices:     "{{ blkvols.stdout_lines|regex_replace('sd','/dev/sd') }}"
  when:          blkvols.stdout|length > 0 and nvmedevs.stdout|length <= 0

- name: block volumes need suffix
  set_fact:
    #sdevices:   "{{ devices | regex_replace('sd([b-z])','sd\\1') }}"
    sdevices:    "{{ item }}{{ blkdevsfx }}"
  with_items:   
  - "{{ devices }}"
  when:          blkvols.stdout|length > 0

- name: debug
  debug:
    msg: "Found {{ ndevices }} devices: {{ devices }} sdevices: {{ sdevices }}"

