# Copyright (c) 1999, 2018, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl

- name: list host map for this play
  debug: 
    msg: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  with_items: "{{ ansible_play_hosts }}"

- name: ensure security notification package installed; install nc for trouble shooting
  yum:
    name:        ['yum-plugin-security','nc']
    state:       latest
  become:        true
  become_user:   root

- stat:
    path:        "{{ initfile }}"
  register:      initdone
  become:        true
  become_user:   root

- name: update any packages where security errata available
  yum:
    name:        '*'
    state:       latest
    security:    true
  become:        true
  become_user:   root
  when:          initdone.stat.exists == false and securityupdates == "true"


- name: copy keys for opc user
  copy:
    content:        "{{ key }}"
    dest:           "{{ keyfile }}"
    owner:          opc
    group:          opc
    mode:           0400
    force:          no

- name: synchronize service directory
  synchronize: 
    src:            "{{ servicedir }}"
    dest:           "{{ opchome }}"
  when:             inventory_hostname in groups['srvrhosts']

- name: set up dns
  import_tasks:     "roles/common/tasks/dns.yml"

# creates "{{ initfile }}" used to decide if already initialized
- name: create a cron file to check for security updates
  cron:
    name:        yum list cves
    weekday:     0-6
    minute:      0
    hour:        1
    user:        root
    job:         "/usr/bin/yum updateinfo -y list cves > /home/opc/latest-cves"
    cron_file:   yum-latestcves
  become:        true
  become_user:   root
  when:          initdone.stat.exists == false

