# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
#
# stop db
# stop service
# dbclose, dbunload
# ttdaemonadmin stop
---

- name: set db service paths
  include_tasks:    roles/datainstances/tasks/dbsetpaths.yaml

- name: check whether systemd control files installed
  stat:
    path:           "{{ systemddir }}/{{ dbservicename }}"
  register:         systemdsvcfile
  become:           true
  become_user:      root

- name: stop db service
  systemd:
    name:           "{{ dbservicename }}"
    enabled:        false
    state:          stopped
  register:         sysctl
  become:           true
  become_user:      root
  when:             systemdsvcfile.stat.exists

- name: check db service state (stopped expected)
  debug:
    msg: "service: {{ sysctl.name }}, enabled: {{ sysctl.enabled }}, state: {{ sysctl.state }}"
  when:            systemdsvcfile.stat.exists

- name: attempt daemon stop
  shell:            "{{ ttinstancepath }}/bin/ttdaemonadmin -stop -force"
  register:         ttstop
  become:           true
  become_user:      oracle
  failed_when:      ttstop.rc > 1

- name: display status (daemon not running)
  debug:
    msg:            "{{ ttstop.stderr_lines }}"
  ignore_errors:    true


