# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
#
# stop db
# stop service
# dbclose, dbunload
# ttdaemonadmin stop
---


- name: attempt close (stoptimeout=={{ stoptimeout }})
  shell:            "{{ mgmt }} ttgridadmin dbclose {{ dbname }} -wait {{ stoptimeout }}"
  register:         dbclose
  become:           true
  become_user:      oracle
  #ignore_errors:    true
  run_once:         true
  # fail on timeout or internal error
  failed_when:      dbclose.rc in [253,255]

- name: attempt unload (stoptimeout=={{ stoptimeout }})
  shell:            "{{ mgmt }} ttgridadmin dbunload {{ dbname }} -wait {{ stoptimeout }}"
  register:         dbload
  become:           true
  become_user:      oracle
  #ignore_errors:    true
  run_once:         true
  # fail on timeout or internal error
  failed_when:      dbload.rc in [253,255]
  # don't run when dbclose says instance is down
  when:             dbclose.rc != 252

- name: check whether systemd control files installed
  stat:
    path:           "{{ systemddir }}/{{ dbservicename }}"
  register:         systemdsvcfile
  become:           true
  become_user:      root

- name: stop db service
  systemd:
    name:           "{{ dbservicename }}"
    enabled:        false
    state:          stopped
  register:         sysctl
  become:           true
  become_user:      root
  when:             systemdsvcfile.stat.exists

- name: check db service state (stopped expected)
  debug:
    msg: "service: {{ sysctl.name }}, enabled: {{ sysctl.enabled }}, state: {{ sysctl.state }}"
  when:            systemdsvcfile.stat.exists


- name: check dbstatus
  shell:            "{{ mgmt }} ttgridadmin dbstatus {{ dbname }} --replicaset"
  register:         mgmtstatus
  ignore_errors:    true
  become:           true
  become_user:      oracle
  run_once:         true

- name: display dbstatus
  debug:
    msg:            "{{ mgmtstatus.stdout_lines }}"
  run_once:         true


