# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
---
#
# get client connect information from mgmt server
#

- import_tasks: roles/mgmtinstances/tasks/mgmt-path.yaml

- name: ttgridadmin gridclientexport
  shell:        "{{ mgmt }} ttgridadmin gridclientexport {{ ttgriddir }}/client.odbc.ini"
  args:
    chdir:      "{{ ttgriddir }}"
  become:       true
  become_user:  oracle
  run_once:     true

- name: fetch client ini
  fetch: 
    src:        "{{ ttgriddir }}/client.odbc.ini"
    dest:       "roles/client/tasks/"
    flat:       true
  become:       true
  run_once:     true


  
