# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
---
# install client instances
#

- import_tasks: clientini.yaml
  when:         inventory_hostname in groups['mgmt-addresses']

- import_tasks: clients.yaml
  when:         inventory_hostname in groups['client-addresses']



