# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
#
# orauser variables
#
orakey:       "{{ servicedir }}/ansible/roles/orauser/files/id_rsa"
keydir:       "{{ oraclehome }}/.ssh"
privkey:      "{{ lookup('file', orakey) }}"
publkey:      "{{ lookup('file', orakey + '.pub') }}"
hostsystems:  "{{ oraclehome }}/hosts"
sshopts:      "-o StrictHostKeyChecking=no -o ConnectTimeout=3"
openjdk:      "{{ jdk|regex_search('(openjdk)') }}"
openjdkrt:    "{{ jdk|regex_replace('java','jre') }}"
