# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
---
# stop services

- name: import zk setup
  import_tasks:   roles/zkservers/tasks/zksetup.yaml


- name: stop zookeeper server
  systemd:
    name:         "{{ zksvcname }}"
    enabled:      no
    state:        stopped
  register:       sysctl
  ignore_errors:  true
  become:         true
  become_user:    root
  when:           inventory_hostname in groups['zookeeper-addresses']

- name: disable zookeeper server
  systemd:
    name:         "{{ zksvcname }}"
    enabled:      no
  register:       sysctl2
  ignore_errors:  true
  become:         true
  become_user:    root
  when:           inventory_hostname in groups['zookeeper-addresses']

- name: check state
  debug:
    msg:         "service: {{ sysctl2.name }} enabled: {{ sysctl2.enabled }} active-state: {{ sysctl2.status.ActiveState }}"

