# Copyright (c) 1999, 2018, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
---
# Check deployment status
#

- import_tasks: roles/zkservers/tasks/zkstatus.yml
  when:         inventory_hostname not in groups['client-addresses']

- import_tasks: roles/mgmtinstances/tasks/mgmt-path.yml
  when:         inventory_hostname in groups['mgmt-addresses']

- name: get db status
  shell: "{{ ttinstancedir }}/{{ ttgridname }}_mgmt/bin/ttenv ttgridadmin dbstatus {{ dbname }} -element"
  args:
    chdir:         "{{ ttgriddir }}"
  register:        shell_result  
  become:          true
  become_user:     oracle
  when:            inventory_hostname in groups['mgmt-addresses']
  run_once:        true

- name: display current status
  debug:
    var:           shell_result.stdout_lines
  when:            shell_result is defined and inventory_hostname in groups['mgmt-addresses']
  run_once:        true


- name: any grid connection info?
  stat:
    path:          "{{ ttgriddir }}/service-info.txt"
  register:        serviceinfo
  become:          true
  become_user:     oracle
  when:            inventory_hostname in groups['mgmt-addresses']

- name: get service info if present
  shell:           cat "./service-info.txt"
  args:
    chdir:         "{{ ttgriddir }}"
  register:        service_info
  become:          true
  become_user:     oracle
  run_once:        true
  when:            inventory_hostname in groups['mgmt-addresses'] and serviceinfo.stat.readable

- name: display service info
  debug:
    var:           service_info.stdout_lines
  when:            service_info is defined
  run_once:        true

