# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
---

- name: setup variables 
  import_tasks: zksetup.yaml

# set up service
- name: set up config to run zk as service
  template:
    src:            roles/zkservers/templates/zk.service.j2
    dest:           "{{ systemddir }}/{{ zksvcname }}.service"
    owner:          oracle
    group:          oracle
    mode:           0660
  become:           true
  become_user:      root

- name: run zk as a service
  systemd: 
    name:           "{{ zksvcname }}"
    state:          restarted
    daemon_reload:  true
    enabled:        true
    no_block:       false
  become:           true
  become_user:      root


- name: fetch client file back to ansible controller
  fetch: 
    src:            "{{ zkdatadir }}/zoo_client.conf"
    dest:           "roles/datainstances/files/zoo_client.conf"
    flat:           true
  run_once:         true
  become:           true
  become_user:      oracle

#- name: zk status
#  import_tasks:    zkstatus.yaml



