# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
#
# Be aware of what runs where
# Assumed to be run by root user
# 
---

- name: find path to mgmt instance
  include_tasks:    roles/mgmtinstances/tasks/mgmt-path.yaml

# run service on one instance to establish active
- name: run service
  include_tasks:    roles/mgmtinstances/tasks/mgmt-runsvc.yaml
  run_once:         true

- name: poll for mgmt active up restarttimeout={{ restarttimeout }}
  shell:            "{{ mgmt }} ttgridadmin mgmtstatus | grep Active"
  register:         activeup
  failed_when:      activeup.rc > 1
  until:            activeup.stdout.find("Up") != -1
  retries:          "{{ (restarttimeout|int / 30)|int }}"
  delay:            30
  run_once:         true
  become:           true
  become_user:      oracle

- name: now poll for standby restarttimeout={{ restarttimeout }}
  shell:            "{{ mgmt }} ttgridadmin mgmtstatus | grep Standby"
  register:         activeup
  failed_when:      activeup.rc > 1
  until:            activeup.stdout.find("Up") != -1
  retries:          "{{ (restarttimeout|int / 30)|int }}"
  delay:            30
  run_once:         true
  become:           true
  become_user:      oracle

- name: enable monitoring services
  systemd:
    name:           "{{ dbname }}-{{ item }}"
    enabled:        yes
  with_items:       ['mgmt.service']
  become:           true
  become_user:      root

- name: start monitoring service
  systemd:
    name:           "{{ dbname }}-{{ item }}"
    enabled:        yes
    state:          started
  with_items:       ['mgmt.timer']
  become:           true
  become_user:      root

- name: check status
  shell:            "{{ mgmt }} ttgridadmin mgmtstatus"
  register:         mgmtstatus
  run_once:         true
  become:           true
  become_user:      oracle
  ignore_errors:    true

- debug:
    msg:            "{{ mgmtstatus.stdout_lines }}"
  when:             mgmtstatus is defined
  run_once:         true



