# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
#
# run data instances as service under systemd
---

- name: set db service paths
  include_tasks:    roles/datainstances/tasks/dbsetpaths.yaml

- name: check whether db systemd control files already installed
  stat:
    path:           "{{ systemddir }}/{{ dbservicename }}"
  register:         systemdsvcfile
  become:           true
  become_user:      root

- name: install db service files from templates
  template:
    src:            "roles/mgmtinstances/templates/{{ item }}.j2"
    dest:           "{{ systemddir }}/{{ dbservicename }}"
    owner:          oracle
    group:          oracle
    mode:           0644
  with_items:       ['db.service']
  when:             systemdsvcfile.stat.isdir is undefined
  become:           true
  become_user:      root

- name: disable db service before start
  systemd:
    name:           "{{ dbservicename }}"
    enabled:        no
  register:         disabled
  become:           true
  become_user:      root
  ignore_errors:    true

- name: enable db service
  systemd:
    name:           "{{ dbservicename }}"
    enabled:        yes
    state:          started
  register:         dbe
  become:           true
  become_user:      root

- name: display db instance status
  debug:
    msg:            "service: {{ dbe.name }}, enabled: {{ dbe.enabled }}, state: {{ dbe.state }}"


