# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
---
# Check deployment status
#
- import_tasks:    roles/mgmtinstances/tasks/mgmt-path.yaml
  when:            inventory_hostname in groups['mgmt-addresses']

- name: check mgmt status
  shell:            "{{ mgmt }} ttgridadmin mgmtstatus"
  register:         mgmtstatus
  become:           true
  become_user:      oracle
  run_once:         true

- name: display mgmt status
  debug:
    msg:            "{{ mgmtstatus.stdout_lines }}"
  run_once:         true

  
- set_fact:
    mgmtisdown:     "{{ mgmtstatus.stdout.find('Down') != -1 }}"  

- name: get db status
  shell:           "{{ mgmt }} ttgridadmin dbstatus -all"
  args:
    chdir:         "{{ ttgriddir }}"
  register:        shell_result2  
  become:          true
  become_user:     oracle
  when:            not mgmtisdown 
  ignore_errors:   true

- name: display current status
  debug:
    var:           shell_result2.stdout_lines
  when:            not mgmtisdown  and shell_result2 is defined
  run_once:        true


- name: get instance list
  shell:           "{{ mgmt }} ttgridadmin instancelist"
  args:
    chdir:         "{{ ttgriddir }}"
  register:        shell_result1
  become:          true
  become_user:     oracle
  when:            not mgmtisdown  and shell_result2.rc == 0
  run_once:        true

- name: display instance list
  debug:
    var:           shell_result1.stdout_lines
  when:            not mgmtisdown  and shell_result1 is defined
  run_once:        true


