# Copyright (c) 1999, 2018, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
---
# Check deployment status
#
- import_tasks:    roles/mgmtinstances/tasks/mgmt-path.yml
  when:            inventory_hostname in groups['mgmt-addresses']

- name: get instance list
  shell:           "{{ mgmt }} ttgridadmin instancelist"
  args:
    chdir:         "{{ ttgriddir }}"
  register:        shell_result1
  become:          true
  become_user:     oracle
  when:            mgmt is defined and inventory_hostname in groups['mgmt-addresses']
  run_once:        true

- name: display instance list
  debug:
    var:           shell_result1.stdout_lines
  when:            shell_result1 is defined and inventory_hostname in groups['mgmt-addresses']
  run_once:        true

- name: get db status
  shell:           "{{ mgmt }} ttgridadmin dbstatus -all"
  args:
    chdir:         "{{ ttgriddir }}"
  register:        shell_result2  
  become:          true
  become_user:     oracle
  when:            mgmt is defined and inventory_hostname in groups['mgmt-addresses']
  run_once:        true

- name: display current status
  debug:
    var:           shell_result2.stdout_lines
  when:            shell_result2 is defined and inventory_hostname in groups['mgmt-addresses']
  run_once:        true

