# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
---
# Run ttgridrollout to set up grid and database
# Only run on ansible controller, first db instance
#
- import_tasks: mgmtinstancesetup.yaml
  become:       true
  when:         inventory_hostname in groups['mgmt-addresses']

- import_tasks: create-grid.yaml
  run_once:     true
  when:         inventory_hostname in groups['mgmt-addresses']

- import_tasks: mgmt-service.yaml
  when:         inventory_hostname in groups['mgmt-addresses']

# only on data instances
- import_tasks: roles/mgmtinstances/tasks/db-service.yaml
  when:         inventory_hostname in groups['db-addresses']

