# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
---
#
# Set up host to be management instance
#
- name: install handy-dandy utils
  yum: 
    name:      ['nc','numactl','dstat']
    state:     latest
  become:      true
  become_user: root

- name: open mgmt daemon, c/s, replication firewall ports
  firewalld:
    permanent: true
    immediate: true
    port:      "{{ item }}/tcp"
    state:     enabled
    source:    "{{ cidr }}"
  with_items:
    - "{{ mgmtdaemonport }}"
    - "{{ mgmtcsport }}"
    - "{{ mgmtreplport }}"
  become:      true
  become_user: root

- name: create instance directory
  file: 
    path:           "{{ ttinstancedir }}"
    owner:          oracle
    group:          oracle
    mode:           0770
    state:          directory
  become:           true
  become_user:      root

- name: create grid directory for configuration files
  file:
    state:     directory
    path:      "{{ ttgriddir }}"
    owner:     oracle
    group:     oracle
    mode:      0770
  become:      true
  become_user: oracle

- name: create bin directory for tools
  file:
    state:     directory
    path:      "{{ oraclehome }}/bin"
    owner:     oracle
    group:     oracle
    mode:      0770
  become:      true
  become_user: oracle

- name: copy in commands utilities
  copy: 
    src:       "{{ opchome }}/{{ scriptdir }}/{{ item }}"
    dest:      "{{ oraclehome }}/bin/{{ item }}"
    owner:     oracle
    group:     oracle
    mode:      0750
  with_items:  ['runcmds.py', 'mgmtexamine.py', 'scaleout.py', 'dbloadready.py']
  become:      true
  become_user: oracle

