# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl

- hosts: zookeeper-addresses mgmt-addresses db-addresses
  any_errors_fatal: true
  roles:
    - common
    - orauser

