# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
#
# start
# ansible-playbook [ -e starttime=<time-in-seconds> | -e starttime="" ] ...
#   zkServer.sh start
#   start primary mgmtinstance
#   start standby mgmtinstance
#   start datainstances
#   dbload -wait [time], dbopen -wait [time]

- import_playbook: zkrestart.yaml
- import_playbook: mgmtrestart.yaml
- import_playbook: dbrestart.yaml



