# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
# 
# top level playbook 
- import_playbook: bastion.yaml
- import_playbook: orauser.yaml
- import_playbook: zookeeper.yaml
- import_playbook: datainstances.yaml
- import_playbook: mgmtinstances.yaml
- import_playbook: client.yaml

- hosts: mgmt-addresses
  pre_tasks:
  - import_tasks: include.yaml

  tasks:
  - import_tasks: roles/mgmtinstances/tasks/service-info.yaml
