# Copyright (c) 1999, 2018, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
# 
# top level playbook 
- import_playbook: bastion.yml
- import_playbook: orauser.yml
- import_playbook: zookeeper.yml
- import_playbook: datainstances.yml
- import_playbook: mgmtinstances.yml
- import_playbook: client.yml

- hosts: mgmt-addresses
  pre_tasks:
  - import_tasks: include.yml

  tasks:
  - import_tasks: roles/mgmtinstances/tasks/service-info.yml
