# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
#
# scaleout to add more data instances
#
- hosts: db-addresses 

  roles:
    - common
    - orauser
    - datainstances

- hosts: mgmt-addresses db-addresses

  pre_tasks:
  - import_tasks: include.yaml

  roles:
    - scaleout

- import_playbook: client.yaml

