# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl

# check zookeeper
- hosts: zookeeper-addresses

  pre_tasks:
  - import_tasks: include.yaml

  tasks:
  - import_tasks: roles/zkservers/tasks/zkstatus.yaml
    vars:
      zkinstalldir: zookeeper

# print dbstatus
- hosts: mgmt-addresses

  pre_tasks:
  - import_tasks: include.yaml

  tasks:
  - import_tasks: roles/mgmtinstances/tasks/dbstatus.yaml

