# Copyright (c) 1999, 2019, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
---

- include_vars: roles/common/vars/main.yaml
- include_vars: roles/common/defaults/main.yaml

- import_tasks: orauser.yaml

- import_tasks: install-pkgs.yaml
  become:       true
  become_user:  oracle

- import_tasks: ssh.yaml
  become:       true
  become_user:  oracle
  when:         inventory_hostname in groups['srvrhosts']



  

