# Copyright (c) 1999, 2018, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
---

- include_vars: roles/common/vars/main.yml
- include_vars: roles/common/defaults/main.yml

- import_tasks: orauser.yml

- import_tasks: kernel.yml
  become:       true
  become_user:  root
  when:         inventory_hostname in groups['db-addresses']

- import_tasks: install-pkgs.yml
  become:       true
  become_user:  oracle

- import_tasks: ssh.yml
  become:       true
  become_user:  oracle
  when:         inventory_hostname in groups['srvrhosts']



  

